eureka:
    instance:
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 3
    client:
        register-with-eureka: true
        service-url:
            default-zone:  http://localhost:9761/eureka/
spring: 
    application:
        name: admin-server
    boot:
        admin:
            url: http://localhost:${server.port}
            turbine:
                clusters: default
                location: admin-server #turbine server serviceId
#javamelody:
#    collectserver.enabled: true
#    init-parameters:
#        storage-directory: G:/tmp/javamelody
#turbine: 
#    appConfig: BLACKBOOK-DEV-SERVICE #配置Eureka中的serviceId列表，表明监控哪些服务
#    aggregator: 
#        clusterConfig: default #指定聚合哪些集群，多个使用”,”分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
#        clusterNameExpression: new String("default")